### ISSUE TITLE
Move config.js to top level directory

### ISSUE THREAD

**Issue by GunshipPenguin** [SentiSocial/sentisocial-backend#29]
Also add information about settings.js to README

**Comment by GunshipPenguin** [comment]
Also, there are some outdated config values and comments in there, those should be cleaned up also

**Comment by morrme** [comment]
I am happy to jump in and move the file for you, but I'm not sure if I can tell what items within the file should be removed.

**Comment by omarchehab98** [comment]
@GunshipPenguin

**Comment by GunshipPenguin** [comment]
Done
