### ISSUE TITLE
Tweet Language Detection

### ISSUE THREAD

**Issue by omarchehab98** [SentiSocial/sentisocial-backend#30]
@GunshipPenguin I remember we ran into non-English tweets during the hackathon.

If I am not mistaken, we solved that by limiting tweets to the US.

Check out this package, it can help us with expanding our location filtering globally while maintaining our tweets to be English.
https://github.com/wooorm/franc

Also, as a bonus, this package will be a step closer for multi-language support, if it is something we would want to consider in the future.

**Comment by DennisTDev** [comment]
![image](https://cloud.githubusercontent.com/assets/11730903/23310974/6a6d147c-fa82-11e6-8de2-42b95e493dfd.png)

Example of trending topic not in English.

**Comment by GunshipPenguin** [comment]
f880d6a81b5c64244133799aefeff429e6f48487 Limits tweets analyzed to English only.

Detecting if trends are English or Spanish is harder, but should be pretty rare from now on so I'm closing this. May have to reopen if trends in other languages start to crop up more. 

Also, if we need to detect the language of a tweet, we don't need to use another package, the Twitter API already gives us that information (https://dev.twitter.com/overview/api/tweets) (scroll down to the 'lang' field)
